"""add next_service and image_after columns

Revision ID: 1a6061d05616
Revises: e94d827b912d
Create Date: 2026-06-03 16:25:44.164485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6061d05616'
down_revision = 'e94d827b912d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generator_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_service', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_after', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_log', schema=None) as batch_op:
        batch_op.drop_column('image_after')

    with op.batch_alter_table('generator_log', schema=None) as batch_op:
        batch_op.drop_column('next_service')

    # ### end Alembic commands ###
