"""Added timestamp and MaintenanceTask

Revision ID: e94d827b912d
Revises: 
Create Date: 2026-06-03 01:30:37.489583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94d827b912d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_report', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
